### ISSUE TITLE
Thắc mắc về hàm onUnmount trong constructor

### ISSUE THREAD

**Issue by m-inh** [quanla/pure-react-sample-coffee#3]
Dear anh Quân,

Em đã đọc qua ví dụ về user-info và r-component thì có thấy a viết hàm onChange (trong user-infor) bằng Higher order function với 3 level:
1. Bao đóng đối tượng listener
2. Bao đóng thêm đối tượng handler, đẩy handler vào mảng changeListeners.
3. Xóa handler khỏi changeListeners

Và khi sử dụng thì sử dụng một lời gọi hàm duy nhất:
https://github.com/quanla/pure-react-sample-coffee/blob/143a1036741a4ea249279f1666e9f34348eacd49/src/client/coffee-app/coffee-app.jsx#L13

Khi mới đầu đọc code bên component sử dụng thì e thắc mắc: tại sao có xóa listener mà không thấy dòng thêm listener. Kiểu như dòng: `this.onMount(handler)`. tới khi e đọc hàm addRemove trong Cols mới hiểu.

Thắc mắc của em là tại sao anh không viết tách riêng level 3 ra một hàm khác và coi như một action riêng biệt, như thế khi đọc code sẽ dễ hiểu hơn không?

ý tưởng là trong hàm constructor sẽ như sau:
```
constructor () {
  const handler = () => { ... };

  this.onMount(handler);
  this.onUnmount(handler);
}
```

Cám ơn anh!

**Comment by quanla** [comment]
1. Tại mình thích ngắn gọn
2. Tại mình không muốn có thêm 1 biến "handler" trong constructor, vì nếu
sau này cần khai báo gì thêm thì sẽ lại phải đổi tên thành handler1 và
handler2...

**Comment by m-inh** [comment]
ok anh
